# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sentri_vault?currentSchema=sentri_vault_schema
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.open-in-view=false
spring.sql.init.continue-on-error=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# To create and drop the
spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=create --- can be set to 'none' so that we only execute from schema.sql
# To show sql commands in the terminal
spring.jpa.show-sql=true
# So that we can insert data using data.sql
spring.sql.init.mode=always

spring.jpa.properties.hibernate.format_sql=true

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## Additional Properties
# Condition to create dummy records
sentri.application.manual-db-populate=true
sentri.application.schema=sentri_vault_schema